"use client";
import Link from "@/app/components/SiteLink";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Compass, Layers3, MapPin, Menu, MousePointer2, X } from "lucide-react";
import { MapArtwork } from "@/app/components/Visuals";
const services=[
 {n:"01",title:"Продвижение в 2ГИС",text:"Аудит и развитие карточки организации.",href:"/uslugi/prodvizhenie-2gis",icon:MapPin,theme:"green"},
 {n:"02",title:"Яндекс Карты",text:"Оформление и продвижение в геосервисе.",href:"/uslugi/yandex-karty",icon:Compass,theme:"cream"},
 {n:"03",title:"Сайты под ключ",text:"Структура, дизайн и адаптивная разработка.",href:"/uslugi/sozdanie-saitov",icon:Layers3,theme:"blue"},
 {n:"04",title:"Интернет-реклама",text:"Подбор инструментов под задачу бизнеса.",href:"/uslugi/reklama",icon:MousePointer2,theme:"coral"},
];
function Reveal({children,className=""}:{children:React.ReactNode,className?:string}){return <div className={`reveal ${className}`}>{children}</div>}
export default function Home(){const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false);useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>40);window.addEventListener("scroll",onScroll);const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>obs.observe(el));const key=(e:KeyboardEvent)=>e.key==="Escape"&&setMenu(false);window.addEventListener("keydown",key);return()=>{window.removeEventListener("scroll",onScroll);window.removeEventListener("keydown",key);obs.disconnect()}},[]);const nav=[ ["Услуги","/uslugi"],["Кейсы","/kejsy"],["О компании","/o-kompanii"],["Калькулятор лидов","/kalkulyator"],["FAQ","/voprosy"],["Контакты","/kontakty"] ];return <main>
<header className={`header ${scrolled?"scrolled":""}`}><Link href="/" className="brand"><span className="brand-mark">D<span>·</span></span><span>DIGITAL<br/>STUDIO</span></Link><nav className="desktop-nav">{nav.slice(0,4).map(([a,b])=><Link href={b} key={a}>{a}</Link>)}</nav><Link className="header-cta" href="/kontakty">Обсудить проект <ArrowUpRight size={16}/></Link><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?"Закрыть меню":"Открыть меню"}>{menu?<X/>:<Menu/>}</button></header>
{menu&&<div className="mobile-menu"><button className="menu-close" onClick={()=>setMenu(false)} aria-label="Закрыть"><X/></button>{nav.map(([a,b])=><Link key={a} href={b} onClick={()=>setMenu(false)}>{a}<ArrowUpRight/></Link>)}</div>}
<section className="hero home-hero"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow hero-tag"><i/> DIGITAL-ПРОДВИЖЕНИЕ ДЛЯ БИЗНЕСА <span> / РОССИЯ</span></div><h1>МАРКЕТИНГ,<br/><em>КОТОРЫЙ</em><br/>РАБОТАЕТ<span className="lime-dot">.</span></h1><p>Продвигаем бизнес в 2ГИС и Яндекс Картах, разрабатываем сайты и помогаем выстроить систему привлечения клиентов.</p><div className="hero-actions"><Link className="button button-lime" href="/kontakty">Обсудить проект <ArrowUpRight size={18}/></Link><Link className="button button-ghost" href="/uslugi">Все услуги <ArrowDown size={17}/></Link></div><div className="hero-bottom"><span>НЕ ШУМ. А СИСТЕМА.</span><span>01 — DIGITAL / GROWTH</span></div></div><div className="hero-visual"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="hero-center"><MapPin size={42}/><span>GEO<br/>SIGNAL</span></div><div className="orbit-label label-a">SEARCH / DISCOVER</div><div className="orbit-label label-b">LOCAL / RELEVANT</div><div className="metric-card"><span>ПОИСК РЯДОМ</span><b>Ваша организация</b><small><i/> На карте клиента</small></div><div className="hero-coordinate">GEO<br/>RUSSIA</div><div className="hero-index">[ 01—04 ]</div></div><a className="scroll-note" href="#services">ЛИСТАЙТЕ ВНИЗ <ArrowDown size={15}/></a></section>
<section id="services" className="section services"><div className="section-head"><Reveal><span className="eyebrow">НАПРАВЛЕНИЯ / 01</span><h2>ЧЕМ МОЖЕМ<br/><em>ПОМОЧЬ</em></h2></Reveal><Reveal><p>Для каждого направления — отдельная страница с составом работ и подходом.</p><Link className="text-link" href="/uslugi">Все услуги <ArrowRight size={17}/></Link></Reveal></div><div className="service-grid">{services.map(s=>{const Icon=s.icon;return <Link className={`service-card ${s.theme}`} href={s.href} key={s.n}><div className="service-top"><span>{s.n} / SERVICE</span><ArrowUpRight/></div><div className="service-icon"><Icon size={25}/></div><h3>{s.title}</h3><p>{s.text}</p><span className="service-link">Открыть страницу <ArrowRight size={16}/></span></Link>})}</div></section>
<section className="overview-band"><Reveal><span className="eyebrow">ПОДХОД / 02</span><h2>СНАЧАЛА ЗАДАЧА.<br/><em>ЗАТЕМ ИНСТРУМЕНТ.</em></h2><p>Изучаем контекст бизнеса, согласуем план работ и оцениваем результат по данным.</p><Link className="text-link" href="/o-kompanii">Как мы работаем <ArrowRight size={17}/></Link></Reveal><Link href="/etapy-raboty" className="overview-steps"><span>01 — 05</span><b>Этапы<br/>работы</b><ArrowUpRight/></Link></section>
<section className="section cases home-cases"><div className="section-head"><Reveal><span className="eyebrow">ПОРТФОЛИО / 03</span><h2>ПРОЕКТЫ<br/>И <em>КОНЦЕПЦИИ</em></h2></Reveal><Reveal><p>Показываем демонстрационные концепции отдельно от реальных клиентских кейсов.</p><Link className="text-link" href="/kejsy">Все проекты <ArrowRight size={17}/></Link></Reveal></div><div className="case-grid"><Link href="/kejsy/geo-card" className="case-card case-one"><div className="case-art"><MapArtwork/></div><span className="case-meta">ДЕМО-КОНЦЕПТ / ГЕОМАРКЕТИНГ</span><h3>Карточка локального бизнеса</h3><span className="case-arrow"><ArrowUpRight/></span></Link><Link href="/kejsy/business-site" className="case-card case-two"><div className="case-site"><div className="site-art"><div className="browser-window"><div className="browser-bar"><span/><span/><span/><i>digital / studio</i></div><div className="browser-content"><div className="mock-nav">БРЕНД <span>Услуги　О нас　Контакты　●</span></div><div className="mock-head"><small>ХОРОШИЕ РЕШЕНИЯ НАЧИНАЮТСЯ С</small><b>ЧЁТКОЙ<br/>СТРАТЕГИИ.</b><span>Создаём цифровой опыт для бизнеса.</span><button>Обсудить проект ↗</button></div><div className="mock-photo"/><div className="mock-foot"><b>01 / 04</b><span>Сервисы и продукты</span></div></div></div><div className="mini-window"><span>ДИНАМИКА ПОКАЗАТЕЛЕЙ</span><b>ДАННЫЕ</b><div className="bars">{[24,42,34,61,49,79,68,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></div><span className="case-meta">ДЕМО-КОНЦЕПТ / РАЗРАБОТКА</span><h3>Сайт для сервисной компании</h3><span className="case-arrow"><ArrowUpRight/></span></Link></div></section>
<section className="home-tools"><Reveal><span className="eyebrow">ПОЛЕЗНЫЕ РАЗДЕЛЫ / 04</span><h2>ИЗУЧИТЕ<br/><em>ПОДРОБНЕЕ</em></h2></Reveal><div className="tool-links">{[["Геомаркетинг","/geomarketing","Аудит и продвижение в геосервисах"],["Калькулятор лидов","/kalkulyator","Оценка заявок, продаж, выручки и цены лида"],["Вопросы и ответы","/voprosy","О стоимости, сроках и работе"],["Этапы работы","/etapy-raboty","От обсуждения задачи до анализа"]].map(x=><Link href={x[1]} key={x[0]}><span>{x[0]}</span><small>{x[2]}</small><ArrowUpRight/></Link>)}</div></section>
<section className="home-cta"><span className="eyebrow">СЛЕДУЮЩИЙ ШАГ / 05</span><h2>ОБСУДИМ<br/><em>ВАШУ ЗАДАЧУ?</em></h2><p>Расскажите, что хотите продвинуть или разработать.</p><Link className="button button-lime" href="/kontakty">Перейти к контактам <ArrowUpRight size={18}/></Link></section>
<footer className="footer"><Link href="/" className="brand"><span className="brand-mark">D<span>·</span></span><span>DIGITAL<br/>STUDIO</span></Link><span>Продвижение бизнеса и разработка сайтов</span><nav>{nav.map(([a,b])=><Link key={a} href={b}>{a}</Link>)}<Link href="/privacy">Конфиденциальность</Link></nav><small>© {new Date().getFullYear()} DIGITAL STUDIO</small></footer>
</main>}
