import Link from "@/app/components/SiteLink";
import type { Metadata } from "next";
import { ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { Calculator } from "@/app/components/Calculator";
import { ContactForm } from "@/app/components/ContactForm";
import { InnerHeader } from "@/app/components/InnerHeader";
import { MapArtwork } from "@/app/components/Visuals";

type PageData={title:string;eyebrow:string;intro:string;points:string[]};
const pages:Record<string,PageData>={
 "uslugi":{title:"Услуги для бизнеса",eyebrow:"DIGITAL STUDIO / НАПРАВЛЕНИЯ",intro:"Выберите направление — на отдельной странице собрали, что входит в работу и как начать.",points:["Продвижение в 2ГИС","Продвижение в Яндекс Картах","Разработка сайтов","Интернет-реклама"]},
 "uslugi/prodvizhenie-2gis":{title:"Продвижение в 2ГИС",eyebrow:"УСЛУГИ / 01",intro:"Помогаем локальным компаниям улучшить присутствие в 2ГИС: разбираемся с карточкой, конкурентами и возможностями рекламного размещения.",points:["Аудит карточки и поисковой видимости","Анализ конкурентов и спроса","Оформление карточки: фото, услуги, описания","Настройка рекламного размещения","План улучшений и отслеживание показателей"]},
 "uslugi/yandex-karty":{title:"Продвижение в Яндекс Картах",eyebrow:"УСЛУГИ / 02",intro:"Работаем с карточкой организации в Яндекс Картах и Яндекс Бизнесе: от базового оформления до рекламных активностей и оценки обращений.",points:["Проверка корректности данных организации","Оформление услуг, товаров и публикаций","Разбор локальной конкуренции","Настройка рекламных инструментов","Рекомендации по аналитике и репутации"]},
 "uslugi/sozdanie-saitov":{title:"Разработка сайтов под ключ",eyebrow:"УСЛУГИ / 03",intro:"Проектируем сайт вокруг предложения компании и пути клиента: структура, дизайн, адаптивная разработка и инструменты обращений.",points:["Лендинги, сайты услуг и корпоративные проекты","Прототипирование и дизайн интерфейса","Адаптация для телефонов и планшетов","Техническая SEO-подготовка","Формы заявок и подключение аналитики"]},
 "uslugi/reklama":{title:"Интернет-реклама",eyebrow:"УСЛУГИ / 04",intro:"Подбираем рекламный канал исходя из цели, аудитории и географии. Состав работ и бюджет обсуждаются после знакомства с проектом.",points:["Уточнение цели и целевой аудитории","Оценка спроса и конкурентной среды","Подготовка посадочной страницы и объявлений","Запуск и контроль рекламных кампаний","Регулярный анализ и оптимизация"]},
 "geomarketing":{title:"Геомаркетинг",eyebrow:"НАПРАВЛЕНИЕ / КАРТЫ И ГЕОСЕРВИСЫ",intro:"Помогаем бизнесу стать заметнее в сервисах, где люди ищут организации рядом. Начинаем с аудита карточек и локальной выдачи.",points:["Аудит присутствия в 2ГИС и Яндекс Картах","Проверка данных, категорий и услуг","Анализ конкурентов в нужной локации","Подготовка рекомендаций по продвижению","Оценка показов и обращений по доступной статистике"]},
 "o-kompanii":{title:"О подходе",eyebrow:"DIGITAL STUDIO / О КОМАНДЕ",intro:"Digital Studio помогает бизнесу с геомаркетингом, сайтами и рекламой. Мы не публикуем неподтверждённые цифры и не обещаем гарантированные результаты: каждое решение начинается с задачи и исходных данных.",points:["Сначала разбираемся в задаче и текущей ситуации","Выбираем инструменты под контекст бизнеса","Согласуем объём работ и критерии оценки","Показываем, какие данные можно отслеживать"]},
 "etapy-raboty":{title:"Этапы работы",eyebrow:"КАК МЫ РАБОТАЕМ",intro:"Понятный процесс помогает заранее согласовать объём, сроки и ожидаемый результат работы.",points:["Обсуждаем задачу и цели проекта","Изучаем бизнес, аудиторию и текущие материалы","Готовим план работ и согласуем предложение","Реализуем и проверяем согласованные задачи","Анализируем доступные показатели и планируем следующие шаги"]},
 "kalkulyator":{title:"Калькулятор эффективности",eyebrow:"ИНСТРУМЕНТ / ОЦЕНКА ПОТЕНЦИАЛА",intro:"Укажите исходные данные, чтобы оценить возможную выручку за период размещения. Расчёт ориентировочный и не обещает конкретный финансовый результат.",points:[]},
 "voprosy":{title:"Вопросы и ответы",eyebrow:"FAQ / ПЕРЕД СТАРТОМ",intro:"Ответы на частые вопросы о продвижении в картах, разработке сайтов и формате сотрудничества.",points:[]},
 "kontakty":{title:"Контакты",eyebrow:"НА СВЯЗИ",intro:"Опишите задачу — если автоматическая интеграция с Telegram не настроена, сайт предложит отправить подготовленное сообщение вручную.",points:["Продвижение в 2ГИС и Яндекс Картах","Разработка сайтов под ключ","Аудит и консультация","Работаем с организациями по всей России"]},
 "kejsy":{title:"Проекты и концепции",eyebrow:"ПОРТФОЛИО",intro:"Здесь собраны демонстрационные концепции. Они не являются выполненными клиентскими проектами и не содержат вымышленных результатов.",points:[]},
 "kejsy/geo-card":{title:"Карточка локального бизнеса",eyebrow:"ДЕМО-КОНЦЕПТ / ГЕОМАРКЕТИНГ",intro:"Концепция показывает, как может выглядеть комплексная работа с присутствием локальной компании в геосервисе. Это учебный пример, не клиентский кейс.",points:["Аудит информации и категорий","Структурирование услуг и предложений","План рекламного размещения","Метрики для оценки динамики"]},
 "kejsy/business-site":{title:"Сайт для сервисной компании",eyebrow:"ДЕМО-КОНЦЕПТ / РАЗРАБОТКА",intro:"Визуальная концепция многостраничного сайта с ясным предложением, разделом услуг и формой обращения. Это не опубликованный клиентский проект.",points:["Структура страниц и прототип","Адаптивный визуальный стиль","Формы связи и CTA","Базовая техническая SEO-подготовка"]},
 "privacy":{title:"Конфиденциальность",eyebrow:"ИНФОРМАЦИЯ",intro:"Если Telegram-интеграция настроена, данные из формы передаются через сервер сайта в Telegram Bot API для доставки владельцу сайта. Если интеграция не настроена, сайт не отправляет данные автоматически и предлагает сформировать сообщение для ручной отправки через выбранный мессенджер.",points:["Не вводите в сообщение чувствительные данные","Перед отправкой проверьте содержимое сообщения","При ручной отправке данные обрабатываются выбранным мессенджером по его правилам"]}
};
const services=[["Продвижение в 2ГИС","/uslugi/prodvizhenie-2gis"],["Продвижение в Яндекс Картах","/uslugi/yandex-karty"],["Разработка сайтов под ключ","/uslugi/sozdanie-saitov"],["Интернет-реклама","/uslugi/reklama"]];
const questions=["Сколько стоит продвижение в 2ГИС?","Сколько стоит продвижение в Яндекс Картах?","Можно ли продвигаться сразу в двух сервисах?","Когда появляются первые результаты?","Какие показатели можно отслеживать?","Сколько стоит разработка сайта?","Сколько времени занимает создание сайта?","Можно ли заказать только аудит?","Работаете ли вы с организациями из других городов?","Что необходимо для начала сотрудничества?"];
function SpecialContent({path}:{path:string}){if(path==="uslugi")return <div className="directory-grid">{services.map((x,i)=><Link href={x[1]} key={x[1]} className="directory-card"><span>0{i+1} / НАПРАВЛЕНИЕ</span><b>{x[0]}</b><ArrowUpRight/></Link>)}<Link href="/geomarketing" className="directory-card"><span>05 / НАПРАВЛЕНИЕ</span><b>Геомаркетинг</b><ArrowUpRight/></Link></div>;
if(path==="geomarketing")return <div className="geo-detail"><div className="geo-detail-art"><MapArtwork/></div><div className="geo-detail-links"><Link href="/uslugi/prodvizhenie-2gis">Продвижение в 2ГИС <ArrowUpRight/></Link><Link href="/uslugi/yandex-karty">Продвижение в Яндекс Картах <ArrowUpRight/></Link></div></div>;
if(path==="etapy-raboty")return <div className="inner-details"><span className="eyebrow">ПЯТЬ ШАГОВ</span><div>{pages[path].points.map((x,i)=><article key={x}><span>0{i+1}</span><p><Check size={16}/>{x}</p></article>)}</div></div>;
if(path==="kalkulyator")return <section className="inner-interactive"><Calculator/></section>;
if(path==="voprosy")return <div className="inner-faq">{questions.map((q,i)=><details key={q}><summary><span>{q}</span><b>+</b></summary><p>{i===7?"Да, можно начать с аудита карточки, сайта или рекламных кампаний. По итогам обсудим дальнейшие шаги.":i===8?"Работаем с организациями по всей России. Формат взаимодействия согласуем под задачу.":"Стоимость и сроки зависят от состояния проекта, объёма работ и выбранных инструментов. После знакомства подготовим состав работ и индивидуальное предложение."}</p></details>)}</div>;
if(path==="kontakty")return <section className="inner-interactive contact-inner"><ContactForm/></section>;
if(path==="kejsy")return <div className="directory-grid cases-directory"><Link href="/kejsy/geo-card" className="directory-card"><span>ДЕМО-КОНЦЕПТ / ГЕОМАРКЕТИНГ</span><b>Карточка локального бизнеса</b><ArrowUpRight/></Link><Link href="/kejsy/business-site" className="directory-card"><span>ДЕМО-КОНЦЕПТ / РАЗРАБОТКА</span><b>Сайт для сервисной компании</b><ArrowUpRight/></Link></div>;
return null}
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug:slug.split("/")}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const data=pages[slug.join("/")];return data?{title:`${data.title} — Digital Studio`,description:data.intro}:{title:"Страница не найдена — Digital Studio"}}
export default async function RoutePage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join("/");const data=pages[path];if(!data)return <main className="inner-page"><InnerHeader/><div className="inner-hero"><span className="eyebrow">СТРАНИЦА НЕ НАЙДЕНА / 404</span><h1>ТАКОЙ СТРАНИЦЫ<br/><em>НЕТ.</em></h1><Link className="button button-lime" href="/">На главную <ArrowLeft size={17}/></Link></div></main>;
return <main className="inner-page"><InnerHeader/><section className="inner-hero"><Link href="/" className="back-link"><ArrowLeft size={15}/> На главную</Link><span className="eyebrow">{data.eyebrow}</span><h1>{data.title.split(" ").map((w,i)=><span key={i}>{w}{i===data.title.split(" ").length-1?<em>.</em>:" "}</span>)}</h1><p>{data.intro}</p>{!['kalkulyator','voprosy'].includes(path)&&<Link className="button button-lime" href="/kontakty">Обсудить задачу <ArrowUpRight size={17}/></Link>}</section>{path==="etapy-raboty"||path==="kontakty"||path==="kalkulyator"||path==="voprosy"||path==="uslugi"||path==="geomarketing"||path==="kejsy"?<SpecialContent path={path}/>:<section className="inner-details"><span className="eyebrow">ЧТО ВХОДИТ В РАБОТУ</span><div>{data.points.map((x,i)=><article key={x}><span>0{i+1}</span><p><Check size={16}/>{x}</p></article>)}</div></section>}<InnerFooter/></main>}
function InnerFooter(){return <footer className="footer"><Link href="/" className="brand"><span className="brand-mark">D<span>·</span></span><span>DIGITAL<br/>STUDIO</span></Link><span>Продвижение бизнеса и разработка сайтов</span><nav><Link href="/uslugi">Услуги</Link><Link href="/etapy-raboty">Этапы</Link><Link href="/voprosy">FAQ</Link><Link href="/privacy">Конфиденциальность</Link></nav><small>© {new Date().getFullYear()} DIGITAL STUDIO</small></footer>}
