import Link from "@/app/components/SiteLink";
import { Brand } from "@/app/components/Brand";
import type { Metadata } from "next";
import { ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { Calculator } from "@/app/components/Calculator";
import { ContactForm } from "@/app/components/ContactForm";
import { InnerHeader } from "@/app/components/InnerHeader";
import { MapArtwork } from "@/app/components/Visuals";
import { MercedesProjectCard } from "@/app/components/MercedesProjectCard";
import { MercedesCaseStudy } from "@/app/components/MercedesCaseStudy";
import { BundlePricing, CooperationTerms, MapFollowup, MapPricing, MonthlyPricing, SitePricing } from "@/app/components/PricingSections";
import { adsTariff, bundleTariff, careTariff, contactHref, formatPrice, mapTariffs, siteTariffs, tariffPrice } from "@/app/data/tariffs";

type PageData={title:string;eyebrow:string;intro:string;points:string[]};
const pages:Record<string,PageData>={
 "uslugi":{title:"Услуги для бизнеса",eyebrow:"KOREMO / НАПРАВЛЕНИЯ",intro:"Разработка сайтов, упаковка карточек в 2ГИС и Яндекс Картах, ежемесячное сопровождение и реклама. Ниже — состав тарифов, цены и условия работы.",points:["Продвижение в 2ГИС","Продвижение в Яндекс Картах","Разработка сайтов","Интернет-реклама"]},
 "uslugi/prodvizhenie-2gis":{title:"Продвижение в 2ГИС",eyebrow:"УСЛУГИ / 01",intro:"Помогаем локальным компаниям улучшить присутствие в 2ГИС: разбираемся с карточкой, конкурентами и возможностями рекламного размещения.",points:["Аудит карточки и поисковой видимости","Анализ конкурентов и спроса","Упаковка карточки: фото, услуги, описания","Отдельная услуга по сопровождению рекламного размещения","План улучшений и отслеживание доступных показателей"]},
 "uslugi/yandex-karty":{title:"Продвижение в Яндекс Картах",eyebrow:"УСЛУГИ / 02",intro:"Работаем с карточкой организации в Яндекс Картах и Яндекс Бизнесе: от упаковки карточки до рекламных активностей и оценки обращений.",points:["Проверка корректности данных организации","Оформление услуг, товаров и публикаций","Разбор локальной конкуренции","Настройка рекламных инструментов","Рекомендации по аналитике и репутации"]},
 "uslugi/sozdanie-saitov":{title:"Разработка сайтов под ключ",eyebrow:"УСЛУГИ / 03",intro:"Проектируем сайт вокруг предложения компании и пути клиента: структура, дизайн, адаптивная разработка и инструменты обращений.",points:["Лендинги, сайты услуг и корпоративные проекты","Прототипирование и дизайн интерфейса","Адаптация для телефонов и планшетов","Техническая SEO-подготовка","Формы заявок и подключение аналитики"]},
 "uslugi/reklama":{title:"Интернет-реклама",eyebrow:"УСЛУГИ / 04",intro:"Подбираем рекламный канал исходя из цели, аудитории и географии. Состав работ и бюджет обсуждаются после знакомства с проектом.",points:["Уточнение цели и целевой аудитории","Оценка спроса и конкурентной среды","Подготовка посадочной страницы и объявлений","Запуск и контроль рекламных кампаний","Регулярный анализ и оптимизация"]},
 "uslugi/biznes-v-onlayne":{title:"Бизнес в онлайне",eyebrow:"КОМПЛЕКСНОЕ ПРЕДЛОЖЕНИЕ",intro:"Продающий сайт и упаковка карточек в 2ГИС и Яндекс Картах в одном пакете. Состав и условия — ниже.",points:[]},
 "geomarketing":{title:"Геомаркетинг",eyebrow:"НАПРАВЛЕНИЕ / КАРТЫ И ГЕОСЕРВИСЫ",intro:"Помогаем бизнесу стать заметнее в сервисах, где люди ищут организации рядом. Начинаем с аудита карточек и локальной выдачи.",points:["Аудит присутствия в 2ГИС и Яндекс Картах","Проверка данных, категорий и услуг","Анализ конкурентов в нужной локации","Подготовка рекомендаций по продвижению","Оценка показов и обращений по доступной статистике"]},
 "o-kompanii":{title:"О подходе",eyebrow:"KOREMO / О КОМАНДЕ",intro:"KOREMO — сайты и продвижение для локального бизнеса. Создаём сайты, развиваем присутствие в геосервисах и настраиваем рекламу. Мы не публикуем неподтверждённые цифры и не обещаем гарантированные результаты: каждое решение начинается с задачи и исходных данных.",points:["Сначала разбираемся в задаче и текущей ситуации","Выбираем инструменты под контекст бизнеса","Согласуем объём работ и критерии оценки","Показываем, какие данные можно отслеживать"]},
 "etapy-raboty":{title:"Этапы работы",eyebrow:"КАК МЫ РАБОТАЕМ",intro:"Понятный процесс помогает заранее согласовать объём, сроки и ожидаемый результат работы.",points:["Обсуждаем задачу и цели проекта","Изучаем бизнес, аудиторию и текущие материалы","Готовим план работ и согласуем предложение","Реализуем и проверяем согласованные задачи","Анализируем доступные показатели и планируем следующие шаги"]},
 "kalkulyator":{title:"Калькулятор лидов",eyebrow:"ИНСТРУМЕНТ / ОЦЕНКА ПОТЕНЦИАЛА",intro:"Укажите число лидов, средний чек, конверсию, цену пакета и срок размещения. Калькулятор оценит количество продаж, выручку и стоимость одного лида.",points:[]},
 "voprosy":{title:"Вопросы и ответы",eyebrow:"FAQ / ПЕРЕД СТАРТОМ",intro:"Ответы на частые вопросы о продвижении в картах, разработке сайтов и формате сотрудничества.",points:[]},
 "kontakty":{title:"Контакты",eyebrow:"НА СВЯЗИ",intro:"Опишите задачу — если автоматическая интеграция с Telegram не настроена, сайт предложит отправить подготовленное сообщение вручную.",points:["Продвижение в 2ГИС и Яндекс Картах","Разработка сайтов под ключ","Аудит и консультация","Работаем с организациями по всей России"]},
 "kejsy":{title:"Проекты и концепции",eyebrow:"ПОРТФОЛИО",intro:"Здесь собраны реализованные клиентские проекты и демонстрационные концепции. Учебные примеры отмечены отдельно.",points:[]},
 "kejsy/mercedes-amg":{title:"Mercedes AMG",eyebrow:"РЕАЛИЗОВАННЫЙ ПРОЕКТ / РАЗРАБОТКА САЙТОВ",intro:"Сайт для специализированного автосервиса Mercedes-Benz в Сочи.",points:[]},
 "kejsy/geo-card":{title:"Карточка локального бизнеса",eyebrow:"ДЕМО-КОНЦЕПТ / ГЕОМАРКЕТИНГ",intro:"Концепция показывает, как может выглядеть комплексная работа с присутствием локальной компании в геосервисе. Это учебный пример, не клиентский кейс.",points:["Аудит информации и категорий","Структурирование услуг и предложений","План рекламного размещения","Метрики для оценки динамики"]},
 "kejsy/business-site":{title:"Сайт для сервисной компании",eyebrow:"ДЕМО-КОНЦЕПТ / РАЗРАБОТКА",intro:"Визуальная концепция многостраничного сайта с ясным предложением, разделом услуг и формой обращения. Это не опубликованный клиентский проект.",points:["Структура страниц и прототип","Адаптивный визуальный стиль","Формы связи и CTA","Базовая техническая SEO-подготовка"]},
 "privacy":{title:"Обработка данных",eyebrow:"ИНФОРМАЦИЯ О ФОРМЕ",intro:"На опубликованном сайте автоматическая отправка заявки не подключена. После заполнения формы текст сообщения остаётся в вашем браузере; вы сами выбираете адресата и подтверждаете отправку через мессенджер. Это техническое описание формы, не утверждённая политика обработки персональных данных.",points:["Не указывайте в сообщении чувствительные сведения","Перед отправкой проверьте содержание и адресата","При ручной отправке данные обрабатываются выбранным мессенджером по его правилам","Утверждённые документы и сведения об операторе будут размещены после получения их от владельца KOREMO"]}
};
const services=[
 {title:"Продвижение в 2ГИС",href:"/uslugi/prodvizhenie-2gis",description:"Упаковка карточки и отдельные предложения по сопровождению и рекламе.",price:tariffPrice(mapTariffs[0])},
 {title:"Продвижение в Яндекс Картах",href:"/uslugi/yandex-karty",description:"Упаковка карточки и отдельные предложения по сопровождению и рекламе.",price:tariffPrice(mapTariffs[0])},
 {title:"Разработка сайтов под ключ",href:"/uslugi/sozdanie-saitov",description:"Три формата: от сайта-визитки до многостраничного проекта.",price:tariffPrice(siteTariffs[0])},
 {title:"Интернет-реклама",href:"/uslugi/reklama",description:"Сопровождение платных размещений. Рекламный бюджет отдельно.",price:tariffPrice(adsTariff)},
 {title:"Бизнес в онлайне",href:"/uslugi/biznes-v-onlayne",description:"Продающий сайт и упаковка карточек на двух площадках.",price:tariffPrice(bundleTariff)},
 {title:"Геомаркетинг",href:"/geomarketing",description:"Аудит видимости в картах, локального спроса и конкурентов с планом улучшения карточек.",price:""},
];
const questions=["Сколько стоит продвижение в 2ГИС?","Сколько стоит продвижение в Яндекс Картах?","Можно ли продвигаться сразу в двух сервисах?","Когда появляются первые результаты?","Какие показатели можно отслеживать?","Сколько стоит разработка сайта?","Сколько времени занимает создание сайта?","Можно ли заказать только аудит?","Работаете ли вы с организациями из других городов?","Что необходимо для начала сотрудничества?"];
function faqAnswer(index:number){
  if(index===0||index===1)return `Упаковка карточки в выбранном сервисе — ${tariffPrice(mapTariffs[0])}. Упаковка карточек сразу в 2ГИС и Яндекс Картах — ${tariffPrice(mapTariffs[1])}. Сопровождение карточек — ${tariffPrice(careTariff)}; управление платным продвижением оплачивается отдельно.`;
  if(index===2)return `Да. Упакуем карточки на двух площадках за ${tariffPrice(mapTariffs[1])} вместо ${formatPrice(mapTariffs[0].price*2)} по отдельности. Для ежемесячной работы есть сопровождение карточек и отдельная услуга по управлению платным продвижением.`;
  if(index===5)return `Сайт-визитка — ${tariffPrice(siteTariffs[0])}, продающий сайт — ${tariffPrice(siteTariffs[1])}, многостраничный сайт — ${tariffPrice(siteTariffs[2])}. Точная смета зависит от согласованного объёма работ.`;
  if(index===6)return `Сайт-визитка: ${siteTariffs[0].duration}, продающий сайт: ${siteTariffs[1].duration}, многостраничный сайт: ${siteTariffs[2].duration}. Отсчёт после согласования ТЗ, предоплаты и получения материалов.`;
  if(index===7)return "Да, можно начать с аудита карточки, сайта или рекламных кампаний. По итогам обсудим дальнейшие шаги.";
  if(index===8)return "Работаем с организациями по всей России. Формат взаимодействия согласуем под задачу.";
  return "Состав работ и сроки зависят от состояния проекта и выбранных инструментов. После знакомства подготовим индивидуальное предложение.";
}
function SpecialContent({path}:{path:string}){if(path==="uslugi")return <>
<div className="directory-grid services-directory">{services.map((x,i)=><Link href={x.href} key={x.href} className="directory-card service-directory-card"><span className="directory-number">0{i+1} / НАПРАВЛЕНИЕ</span><b>{x.title}</b><p>{x.description}</p>{x.price && <strong className="directory-price">{x.price}</strong>}<span className="directory-more">Состав работ</span><ArrowUpRight className="directory-arrow" aria-hidden="true"/></Link>)}<Link href="/kalkulyator" className="directory-card service-directory-card calculator-directory-card"><span className="directory-number">ИНСТРУМЕНТ / РАСЧЁТ</span><b>Калькулятор лидов</b><p>Оцените продажи, выручку и стоимость одного лида по своим показателям и цене пакета.</p><span className="directory-more">Перейти к расчёту</span><ArrowUpRight className="directory-arrow" aria-hidden="true"/></Link></div>
<SitePricing/><MapPricing/><MonthlyPricing/><BundlePricing/><CooperationTerms/>
<section className="directory-calculator" aria-labelledby="directory-calculator-heading"><div className="directory-calculator-intro"><span className="eyebrow">РАСЧЁТ ПО ВАШИМ ДАННЫМ</span><h2 id="directory-calculator-heading">Калькулятор лидов</h2><p>Введите показатели проекта. Результат пересчитывается автоматически, когда вы меняете значения.</p><Link className="text-link" href="/kalkulyator">Открыть отдельную страницу <ArrowUpRight size={16}/></Link></div><Calculator/></section>
</>;
if(path==="geomarketing")return <div className="geo-detail"><div className="geo-detail-art"><MapArtwork/></div><div className="geo-detail-links"><Link href="/uslugi/prodvizhenie-2gis">Продвижение в 2ГИС <ArrowUpRight/></Link><Link href="/uslugi/yandex-karty">Продвижение в Яндекс Картах <ArrowUpRight/></Link></div></div>;
if(path==="etapy-raboty")return <div className="inner-details"><span className="eyebrow">ПЯТЬ ШАГОВ</span><div>{pages[path].points.map((x,i)=><article key={x}><span>0{i+1}</span><p><Check size={16}/>{x}</p></article>)}</div></div>;
if(path==="kalkulyator")return <section className="inner-interactive"><Calculator/></section>;
if(path==="voprosy")return <div className="inner-faq">{questions.map((q,i)=><details key={q}><summary><span>{q}</span><b>+</b></summary><p>{faqAnswer(i)}</p></details>)}</div>;
if(path==="kontakty")return <section className="inner-interactive contact-inner"><ContactForm/></section>;
if(path==="kejsy")return <div className="portfolio-list"><section className="portfolio-real-section"><div className="portfolio-group-heading"><span className="eyebrow">01 / РЕАЛИЗОВАННЫЕ ПРОЕКТЫ</span><h2>Клиентские работы</h2><p>Опубликованные проекты, выполненные для действующих компаний.</p></div><MercedesProjectCard/></section><section className="portfolio-demo-section"><div className="portfolio-group-heading"><span className="eyebrow">02 / ДЕМОНСТРАЦИОННЫЕ КОНЦЕПЦИИ</span><h2>Концепции</h2><p>Учебные примеры подхода к дизайну и структуре, не клиентские проекты.</p></div><div className="directory-grid cases-directory"><Link href="/kejsy/geo-card" className="directory-card"><span>ДЕМО-КОНЦЕПТ / ГЕОМАРКЕТИНГ</span><b>Карточка локального бизнеса</b><ArrowUpRight/></Link><Link href="/kejsy/business-site" className="directory-card"><span>ДЕМО-КОНЦЕПТ / РАЗРАБОТКА</span><b>Сайт для сервисной компании</b><ArrowUpRight/></Link></div></section></div>;
return null}
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug:slug.split("/")}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const path=slug.join("/");const data=pages[path];const base=process.env.NEXT_PUBLIC_BASE_PATH||"/digital-studio-growth";return data?{title:`${data.title} — KOREMO | Digital Studio`,description:data.intro,alternates:{canonical:`https://korew22220-dev.github.io${base}/${path}.html`}}:{title:"Страница не найдена — KOREMO | Digital Studio"}}
export default async function RoutePage({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join("/");const data=pages[path];if(!data)return <main className="inner-page"><InnerHeader/><div className="inner-hero"><span className="eyebrow">СТРАНИЦА НЕ НАЙДЕНА / 404</span><h1>ТАКОЙ СТРАНИЦЫ<br/><em>НЕТ.</em></h1><Link className="button button-lime" href="/">На главную <ArrowLeft size={17}/></Link></div></main>;
if(path==="kejsy/mercedes-amg")return <main className="inner-page"><InnerHeader/><MercedesCaseStudy/><InnerFooter/></main>;
return <main className="inner-page"><InnerHeader/>
  <section className="inner-hero"><Link href="/" className="back-link"><ArrowLeft size={15}/> На главную</Link><span className="eyebrow">{data.eyebrow}</span><h1>{data.title.split(" ").map((w,i)=><span key={i}>{w}{i===data.title.split(" ").length-1?<em>.</em>:" "}</span>)}</h1><p>{data.intro}</p>{!["kalkulyator","voprosy"].includes(path)&&<Link className="button button-lime" href={path==="uslugi/biznes-v-onlayne"?contactHref(bundleTariff.id):"/kontakty"}>Обсудить задачу <ArrowUpRight size={17}/></Link>}</section>
  {path==="etapy-raboty"||path==="kontakty"||path==="kalkulyator"||path==="voprosy"||path==="uslugi"||path==="geomarketing"||path==="kejsy"?<SpecialContent path={path}/>:data.points.length>0?<section className="inner-details"><span className="eyebrow">ЧТО ВХОДИТ В РАБОТУ</span><div>{data.points.map((x,i)=><article key={x}><span>0{i+1}</span><p><Check size={16}/>{x}</p></article>)}</div></section>:null}
  {path==="uslugi/sozdanie-saitov"&&<><SitePricing/><BundlePricing compact/></>}
  {path==="uslugi/prodvizhenie-2gis"&&<><MapPricing platform="2ГИС"/><MapFollowup/></>}
  {path==="uslugi/yandex-karty"&&<><MapPricing platform="Яндекс Карты"/><MapFollowup/></>}
  {path==="uslugi/reklama"&&<MonthlyPricing advertisingOnly/>}
  {path==="uslugi/biznes-v-onlayne"&&<><BundlePricing/><CooperationTerms/></>}
  <InnerFooter/>
</main>}
function InnerFooter(){return <footer className="footer"><Link href="/" className="brand"><Brand/></Link><span>Сайты и продвижение для локального бизнеса</span><nav><Link href="/uslugi">Услуги</Link><Link href="/kalkulyator">Калькулятор лидов</Link><Link href="/etapy-raboty">Этапы</Link><Link href="/voprosy">FAQ</Link><Link href="/privacy">Обработка данных</Link></nav><small>© {new Date().getFullYear()} KOREMO</small></footer>}
